server:
  servlet:
    context-path: /uaa
  port: 9999
  
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.longmaple: DEBUG
    
      
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka/
        
spring:
  application:
    name: authenticationservice
  security:
    user:
      password: password
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


