server:
  servlet:
    context-path: /productsvr

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
      
spring:
  application:
    name: productservice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  cloud:
    stream:
      bindings:
        inboundVendorChanges:
          destination: vendorChangeTopic
          content-type: application/json
          group: productGroup
      kafka:
        binder:
          brokers: kafkaserver 

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.longmaple: DEBUG
    
redis:
  server: redis
  port: 6379
